name: nails
description: Nail Finder Store
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.2.0
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/ui/

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#0B0B0B"
  image: assets/ui/logo.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: assets/ui/icono.png
